[project]
name = "recipe-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "curl-cffi>=0.14.0",
    "extruct>=0.18.0",
    "parsel>=1.9.1",
    "robotspy>=0.12.0",
    "scrapy>=2.12.0",
]
